# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abrir_chamado.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.chamado import Chamado
from model.usuario import selecionar_id_por_email_senha
import re
from datetime import datetime

class Ui_DialogCreate(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 619)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-11, -1, 861, 651))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineDesc = QtWidgets.QLineEdit(self.frame)
        self.lineDesc.setGeometry(QtCore.QRect(160, 260, 521, 22))
        self.lineDesc.setObjectName("lineDesc")
        self.verdeUserB = QtWidgets.QFrame(self.frame)
        self.verdeUserB.setGeometry(QtCore.QRect(0, -10, 881, 51))
        self.verdeUserB.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB.setObjectName("verdeUserB")
        self.verdeUserB_2 = QtWidgets.QFrame(self.verdeUserB)
        self.verdeUserB_2.setGeometry(QtCore.QRect(0, 0, 881, 51))
        self.verdeUserB_2.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB_2.setObjectName("verdeUserB_2")
        self.verdeUserB_3 = QtWidgets.QFrame(self.frame)
        self.verdeUserB_3.setGeometry(QtCore.QRect(-20, 590, 881, 51))
        self.verdeUserB_3.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB_3.setObjectName("verdeUserB_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(300, 40, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelD = QtWidgets.QLabel(self.frame)
        self.labelD.setGeometry(QtCore.QRect(370, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelD.setFont(font)
        self.labelD.setObjectName("labelD")
        self.labelD_2 = QtWidgets.QLabel(self.frame)
        self.labelD_2.setGeometry(QtCore.QRect(340, 300, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelD_2.setFont(font)
        self.labelD_2.setObjectName("labelD_2")
        self.lineChamado = QtWidgets.QLineEdit(self.frame)
        self.lineChamado.setGeometry(QtCore.QRect(160, 330, 521, 22))
        self.lineChamado.setObjectName("lineChamado")
        self.lineId = QtWidgets.QLineEdit(self.frame)
        self.lineId.setGeometry(QtCore.QRect(160,390, 521, 22))
        self.lineId.setObjectName("lineId")
        self.labelD_3 = QtWidgets.QLabel(self.frame)
        self.labelD_3.setGeometry(QtCore.QRect(360, 360, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelD_3.setFont(font)
        self.labelD_3.setObjectName("labelD_3")
        self.btnChamado = QtWidgets.QPushButton(self.frame)
        self.btnChamado.setGeometry(QtCore.QRect(330, 440, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnChamado.setFont(font)
        self.btnChamado.setStyleSheet("background-color: rgb(49, 255, 26);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnChamado.setObjectName("btnChamado")
      
     
        self.lineTitulo = QtWidgets.QLineEdit(self.frame)
        self.lineTitulo.setGeometry(QtCore.QRect(160, 200, 521, 22))
        self.lineTitulo.setObjectName("lineTitulo")
        self.labelD_4 = QtWidgets.QLabel(self.frame)
        self.labelD_4.setGeometry(QtCore.QRect(300, 160, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelD_4.setFont(font)
        self.labelD_4.setObjectName("labelD_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.lineChamado.setPlaceholderText('local onde ocorreu o problema descrito:')
        self.lineDesc.setPlaceholderText('descreva seu problema:')
        self.lineId.setPlaceholderText('seu id(um numero):')
        self.btnVoltar = QtWidgets.QPushButton(self.frame)
        self.btnVoltar.setGeometry(QtCore.QRect(20, 50, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnVoltar.setFont(font)
        self.btnVoltar.setStyleSheet(
            "background-color: rgb(127, 255, 88);"
            "border-radius: 10px;"
            "border: 2px solid black;"
        )
        self.btnVoltar.setObjectName("btnVoltar")
        self.btnVoltar.setText("Voltar")
        self.btnVoltar.clicked.connect(Dialog.close)
        self.lineTitulo.setPlaceholderText('de um titulo para o problema:')
        self.id_user=None
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Abra um Chamado:"))
        self.labelD.setText(_translate("Dialog", "Descrição:"))
        self.labelD_2.setText(_translate("Dialog", "Local do chamado:"))
        self.labelD_3.setText(_translate("Dialog", "insira seu Id:"))
        self.btnChamado.setText(_translate("Dialog", "Criar chamado"))
       
        self.labelD_4.setText(_translate("Dialog", "Insira um Título ao Chamado:"))
    def criar(self):
      
         descricao = self.lineDesc.text().strip()
         local = self.lineChamado.text().strip()
         id_user = self.lineId.text().strip()
         data_abertura = datetime.now().strftime("%d/%m/%Y")
         titulo=self.lineTitulo.text().strip()
         id_valer=self.id_user
         try:
                 id_user_int = int(id_user)
         except ValueError:
                 QtWidgets.QMessageBox.warning(None, "Ops", "ID deve ser um número válido")
                 return False
         if id_user_int != id_valer:
             QtWidgets.QMessageBox.warning(None, "Ops", "esse não e o seu id")
             return False

         if not re.fullmatch(r'^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\d{4}$', data_abertura):
             QtWidgets.QMessageBox.warning(None, "Ops", "A data deve estar no seguinte formato; dd/mm/aaaa")
             return False

         if not descricao or not local or not data_abertura or not id_user or not titulo:
              QtWidgets.QMessageBox.warning(None,'opa','um dos campos nao foi preenchido')
              return False
         if not re.fullmatch(r'\d+', id_user):
             QtWidgets.QMessageBox.warning(None,'ops','id de user invalido')
             return False
         call=Chamado(descricao=descricao,titulo=titulo,prioridade='media',local=local,id_user=id_user,data_abertura=data_abertura,data_fechamento='',id_adm=None,status='em aberto')
         if call.pegar_id_user():
             msg="""
                  Chamado criado com sucesso!
                 
                 """
             try:
                 call.salvar()
                 QtWidgets.QMessageBox.information(None,'eba',msg)
                 return True
             except:
                  QtWidgets.QMessageBox.warning(None,"erro","id invalido")
                  return False
         else:
             QtWidgets.QMessageBox.warning(None,'erro','id invalido')
             return False
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
