# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.adm_usuario import Adm
import re





class Ui_DialogAdm(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(578, 420)
        self.robloxdecalsinha = QtWidgets.QFrame(Dialog)
        self.robloxdecalsinha.setGeometry(QtCore.QRect(-10, -30, 611, 451))
        self.robloxdecalsinha.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.robloxdecalsinha.setFrameShadow(QtWidgets.QFrame.Raised)
        self.robloxdecalsinha.setObjectName("robloxdecalsinha")
        self.admOk = QtWidgets.QPushButton(self.robloxdecalsinha)
        self.admOk.setGeometry(QtCore.QRect(240, 350, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.admOk.setFont(font)
        self.admOk.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.admOk.setObjectName("admOk")
        
        self.linematricula = QtWidgets.QLineEdit(self.robloxdecalsinha)
        self.linematricula.setGeometry(QtCore.QRect(140, 280, 131, 22))
        self.linematricula.setObjectName("linematricula")
        self.lineSenha = QtWidgets.QLineEdit(self.robloxdecalsinha)
        self.lineSenha.setGeometry(QtCore.QRect(140, 210, 321, 22))
        self.lineSenha.setObjectName("lineSenha")
        self.lineEmail = QtWidgets.QLineEdit(self.robloxdecalsinha)
        self.lineEmail.setGeometry(QtCore.QRect(140, 150, 321, 22))
        self.lineEmail.setObjectName("lineEmail")
        self.lineNome = QtWidgets.QLineEdit(self.robloxdecalsinha)
        self.lineNome.setGeometry(QtCore.QRect(140, 90, 321, 22))
        self.lineNome.setObjectName("lineNome")
        self.nomeAdm = QtWidgets.QLabel(self.robloxdecalsinha)
        self.nomeAdm.setGeometry(QtCore.QRect(260, 60, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nomeAdm.setFont(font)
        self.nomeAdm.setObjectName("nomeAdm")
        self.emailAdm = QtWidgets.QLabel(self.robloxdecalsinha)
        self.emailAdm.setGeometry(QtCore.QRect(260, 120, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.emailAdm.setFont(font)
        self.emailAdm.setObjectName("emailAdm")
        self.senhaAdm = QtWidgets.QLabel(self.robloxdecalsinha)
        self.senhaAdm.setGeometry(QtCore.QRect(260, 180, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.senhaAdm.setFont(font)
        self.senhaAdm.setObjectName("senhaAdm")
        self.matricAdm = QtWidgets.QLabel(self.robloxdecalsinha)
        self.matricAdm.setGeometry(QtCore.QRect(160, 250, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.matricAdm.setFont(font)
        self.matricAdm.setObjectName("matricAdm")
        
        self.lineInstituicao = QtWidgets.QLineEdit(self.robloxdecalsinha)
        self.lineInstituicao.setGeometry(QtCore.QRect(330, 280, 131, 22))
        self.lineInstituicao.setObjectName("lineInstituicao")
        self.labelInst = QtWidgets.QLabel(self.robloxdecalsinha)
        self.labelInst.setGeometry(QtCore.QRect(350, 250, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelInst.setFont(font)
        self.labelInst.setObjectName("labelInst")
        self.verdeBaixo = QtWidgets.QFrame(self.robloxdecalsinha)
        self.verdeBaixo.setGeometry(QtCore.QRect(0, 0, 771, 51))
        self.verdeBaixo.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeBaixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeBaixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeBaixo.setObjectName("verdeBaixo")
        self.verdeBaixo_2 = QtWidgets.QFrame(self.robloxdecalsinha)
        self.verdeBaixo_2.setGeometry(QtCore.QRect(0, 410, 771, 51))
        self.verdeBaixo_2.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeBaixo_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeBaixo_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeBaixo_2.setObjectName("verdeBaixo_2")
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.linematricula.setPlaceholderText('sua matricula')
        self.lineEmail.setPlaceholderText('seu email')
        self.lineNome.setPlaceholderText('seu nome')
        self.lineInstituicao.setPlaceholderText('id da sua Instituicao ')
        self.lineSenha.setPlaceholderText('sua senha:')
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.admOk.setText(_translate("Dialog", "ok"))
        self.nomeAdm.setText(_translate("Dialog", "Nome:"))
        self.emailAdm.setText(_translate("Dialog", "Email:"))
        self.senhaAdm.setText(_translate("Dialog", "Senha:"))
        self.matricAdm.setText(_translate("Dialog", "Matrícula:"))
        self.labelInst.setText(_translate("Dialog", "Instituição"))
    def alt(self):
        nome=self.lineNome.text().strip()
        email=self.lineEmail.text().strip()
        senha=self.lineSenha.text().strip()
        instituicao=self.lineInstituicao.text().strip()
        matricula=self.linematricula.text().strip()
        if not nome or not email or not senha or not instituicao or not matricula:
            QtWidgets.QMessageBox.warning(None, "Campos vazios", "Preencha todos os campos antes de salvar!")
            return False
        if not re.fullmatch(r'[\d-]+', matricula ):
            QtWidgets.QMessageBox.warning(None,"ops",'matricula deve ser numero')
            return False
        elif not re.fullmatch(r'\d+', instituicao):
             QtWidgets.QMessageBox.warning(None,'erro','aqui voce digita o id da instituicao cadastrada')
             return False
        
       
        admin=Adm(nome=nome,senha=senha,instituicao=instituicao,email=email,matricula=matricula)
        if admin.pegar_id_instituicao() :
          try:
                    id_adm=admin.salvar()
                    nome_adm = admin.nome
                    email_adm = admin.email


                    mensagem = f"""
                    Admin salvo com sucesso!
                    seu ID: {id_adm}
                    Nome: {nome_adm}
                    Email: {email_adm}
                    *id e necessario para assumir o chamado
                    """

                    QtWidgets.QMessageBox.information(None, "Confirmação", mensagem)
                    return True
          except:
                    QtWidgets.QMessageBox.warning(None,"erro","id invalido")
                    return False
        else:
             QtWidgets.QMessageBox.warning(None,'erro','esse id nao esta cadastrado')
             return False
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_DialogAdm()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
