# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assumir_chamado.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.chamado import ChamadoAssumido
import re 

class Ui_DialogAssumir(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 619)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-11, -1, 861, 651))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineDesc = QtWidgets.QLineEdit(self.frame)
        self.lineDesc.setGeometry(QtCore.QRect(160, 220, 521, 22))
        self.lineDesc.setObjectName("lineDesc")
        self.verdeUserB = QtWidgets.QFrame(self.frame)
        self.verdeUserB.setGeometry(QtCore.QRect(0, -10, 881, 51))
        self.verdeUserB.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB.setObjectName("verdeUserB")
        self.verdeUserB_2 = QtWidgets.QFrame(self.verdeUserB)
        self.verdeUserB_2.setGeometry(QtCore.QRect(0, 0, 881, 51))
        self.verdeUserB_2.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB_2.setObjectName("verdeUserB_2")
        self.verdeUserB_3 = QtWidgets.QFrame(self.frame)
        self.verdeUserB_3.setGeometry(QtCore.QRect(-20, 590, 881, 51))
        self.verdeUserB_3.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB_3.setObjectName("verdeUserB_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(360, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelD = QtWidgets.QLabel(self.frame)
        self.labelD.setGeometry(QtCore.QRect(330, 180, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelD.setFont(font)
        self.labelD.setObjectName("labelD")
        self.lineIdAdm = QtWidgets.QLineEdit(self.frame)
        self.lineIdAdm.setGeometry(QtCore.QRect(160, 370, 521, 22))
        self.lineIdAdm.setObjectName("lineIdAdm")
        self.lineIdChamado = QtWidgets.QLineEdit(self.frame)
        self.lineIdChamado.setGeometry(QtCore.QRect(160, 450, 521, 22))
        self.lineIdChamado.setObjectName("lineIdChamado")
        self.labelD_3 = QtWidgets.QLabel(self.frame)
        self.labelD_3.setGeometry(QtCore.QRect(360, 410, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelD_3.setFont(font)
        self.labelD_3.setObjectName("labelD_3")
        self.btnAssumeChamado = QtWidgets.QPushButton(self.frame)
        self.btnAssumeChamado.setGeometry(QtCore.QRect(340, 540, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnAssumeChamado.setFont(font)
        self.btnAssumeChamado.setStyleSheet("\n"
"background-color: rgb(127, 255, 88);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnAssumeChamado.setObjectName("btnAssumeChamado")
        self.labelD_5 = QtWidgets.QLabel(self.frame)
        self.labelD_5.setGeometry(QtCore.QRect(270, 260, 301, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelD_5.setFont(font)
        self.labelD_5.setObjectName("labelD_5")
        self.lineDataFecha = QtWidgets.QLineEdit(self.frame)
        self.lineDataFecha.setGeometry(QtCore.QRect(160, 300, 521, 22))
        self.lineDataFecha.setObjectName("lineDataFecha")
        self.labelD_4 = QtWidgets.QLabel(self.frame)
        self.labelD_4.setGeometry(QtCore.QRect(310, 90, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelD_4.setFont(font)
        self.labelD_4.setObjectName("labelD_4")
        self.labelD_6 = QtWidgets.QLabel(self.frame)
        self.labelD_6.setGeometry(QtCore.QRect(360, 340, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelD_6.setFont(font)
        self.labelD_6.setObjectName("labelD_6")
        self.btnBaixa = QtWidgets.QPushButton(self.frame)
        self.btnBaixa.setGeometry(QtCore.QRect(250, 130, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnBaixa.setFont(font)
        self.btnBaixa.setStyleSheet("background-color: rgb(188, 255, 137);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnBaixa.setObjectName("btnBaixa")
        self.btnMedia = QtWidgets.QPushButton(self.frame)
        self.btnMedia.setGeometry(QtCore.QRect(380, 130, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnMedia.setFont(font)
        self.btnMedia.setStyleSheet("background-color: rgb(255, 209, 69);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnMedia.setObjectName("btnMedia")
        self.btnMedia_2 = QtWidgets.QPushButton(self.frame)
        self.btnMedia_2.setGeometry(QtCore.QRect(510, 130, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btnMedia_2.setFont(font)
        self.btnMedia_2.setStyleSheet("background-color: rgb(255, 118, 21);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnMedia_2.setObjectName("btnMedia_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.prioridade_selecionada=None
        self.btnBaixa.clicked.connect(lambda: self.selecionar_prioridade("Baixa"))
        self.btnMedia.clicked.connect(lambda: self.selecionar_prioridade("Média"))
        self.btnMedia_2.clicked.connect(lambda: self.selecionar_prioridade("Alta"))
        self.lineDataFecha.setPlaceholderText('data estimada/real de conclusao')
        self.lineDesc.setPlaceholderText('(em aberto,em andamento,resolvido)')
        self.lineIdAdm.setPlaceholderText('seu id de admin(um numero)')
        self.lineIdChamado.setPlaceholderText('id do chamado que quer editar(um numero)')
    def selecionar_prioridade(self, valor):
        self.prioridade_selecionada = valor

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Chamado:"))
        self.labelD.setText(_translate("Dialog", "Status do Chamado:"))
        self.labelD_3.setText(_translate("Dialog", "Id do chamado:"))
        self.btnAssumeChamado.setText(_translate("Dialog", "Assumir chamado"))
        self.labelD_5.setText(_translate("Dialog", "Data de Fechamento do chamado:"))
        self.labelD_4.setText(_translate("Dialog", "Prioridade do Chamado:"))
        self.labelD_6.setText(_translate("Dialog", "Insira seu Id:"))
        self.btnBaixa.setText(_translate("Dialog", "Baixa"))
        self.btnMedia.setText(_translate("Dialog", "Média"))
        self.btnMedia_2.setText(_translate("Dialog", "Alta"))
    def assumir(self):
        prioridade = self.prioridade_selecionada
        id_adm=self.lineIdAdm.text().strip()
        id_chamado=self.lineIdChamado.text().strip()
        status=self.lineDesc.text().strip().lower()
        data_fechamento=self.lineDataFecha.text().strip()
        status_possivel=['em aberto','resolvido','em andamento']
        if status not in status_possivel:
            QtWidgets.QMessageBox.warning(None,'ops','os stats sao so em aberto,andamento e concluido')
            return False
        if not re.fullmatch(r'^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\d{4}$', data_fechamento):
             QtWidgets.QMessageBox.warning(None, "Ops", "A data deve estar no seguinte formato; dd/mm/aaaa")
             return False
        if not re.fullmatch(r'\d+',id_adm):
             QtWidgets.QMessageBox.warning(None,'ops','id invalido')
             return False
        if not re.fullmatch(r'\d+', id_chamado):
             QtWidgets.QMessageBox.warning(None,'ops','id  invalido')
             return False
        elif not data_fechamento or not id_adm or not id_chamado:
            QtWidgets.QMessageBox.warning(None,'ops','um dos campos nao foi preenchido')
            return False
        elif not prioridade:
            QtWidgets.QMessageBox.warning(None,'ops','selecione uma prioridade')
            return False
        assumido=ChamadoAssumido(descricao='',titulo='',prioridade=prioridade,local='',id_user=None,data_abertura='',data_fechamento=data_fechamento,id_adm=id_adm,status=status)
        if assumido.pegar_id_chamado(id_chamado):
            if assumido.pegar_id_adm():
                try:
                    assumido.atualizar_chamado(id_chamado)
                    QtWidgets.QMessageBox.information(None,'parabens','chamado assumido com sucesso')
                    return True
                except:
                    print('erro')
                    return False
            else:
                QtWidgets.QMessageBox.warning(None,'ops','id de adm inexistente')
                return False
        else:
            QtWidgets.QMessageBox.warning(None,'ops','esse chamado nao existe')
                    
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
