# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chamado_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.chamado import selecionar_chamados
from view.abrir_chamado import Ui_DialogCreate as Ui_create
class Ui_DialogCall(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(737, 627)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-10, -30, 881, 681))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verdeUserB = QtWidgets.QFrame(self.frame)
        self.verdeUserB.setGeometry(QtCore.QRect(-110, 20, 881, 51))
        self.verdeUserB.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB.setObjectName("verdeUserB")
        self.btnCreateCall = QtWidgets.QPushButton(self.frame)
        self.btnCreateCall.setGeometry(QtCore.QRect(300, 140, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnCreateCall.setFont(font)
        self.btnCreateCall.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnCreateCall.setObjectName("btnCreateCall")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(190, 270, 431, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.verdeUserB_2 = QtWidgets.QFrame(Dialog)
        self.verdeUserB_2.setGeometry(QtCore.QRect(-10, 580, 671, 51))
        self.verdeUserB_2.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB_2.setObjectName("verdeUserB_2")
        self.verdeUserB_3 = QtWidgets.QFrame(self.verdeUserB_2)
        self.verdeUserB_3.setGeometry(QtCore.QRect(330, 30, 671, 51))
        self.verdeUserB_3.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB_3.setObjectName("verdeUserB_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnCreateCall.setText(_translate("Dialog", " Adicionar Chamado"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "linha 1 "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "coluna 1"))
class ChamadoUser(QtWidgets.QDialog,Ui_DialogCall):
    def __init__(self):
        super().__init__()
        self.ui = Ui_DialogCall()
        self.ui.setupUi(self)
        self.setWindowTitle("StudyCall - Usuario")

        self.mostrar_chamados()
        self.ui.btnCreateCall.clicked.connect(self.abrir_tela_criar)
    
    def mostrar_chamados(self):
        colunas, resultados = selecionar_chamados()

        self.ui.tableWidget.setRowCount(len(resultados))
        self.ui.tableWidget.setColumnCount(len(colunas))
        self.ui.tableWidget.setHorizontalHeaderLabels(colunas)

        for linha_idx, linha_dados in enumerate(resultados):
            for coluna_idx, valor in enumerate(linha_dados):
                self.ui.tableWidget.setItem(linha_idx, coluna_idx, QtWidgets.QTableWidgetItem(str(valor)))

        self.ui.tableWidget.resizeColumnsToContents()
    
    def abrir_tela_criar(self):
        self.hide()
        self.tela_criar = TelaChamadoCriar()
        self.tela_criar.exec_()
         


class TelaChamadoCriar(QtWidgets.QDialog,Ui_create):
      def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle("StudyCall")
        self.btnChamado.clicked.connect(self.validar_acesso)
      def validar_acesso(self):
          if self.criar():
              self.voltar()
      def voltar(self):
        self.hide()
        self.tela_chamados = ChamadoUser()  
        self.tela_chamados.show()



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     janela = ChamadoUser() 
#     janela.show()
#     sys.exit(app.exec_())
