# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chamado_adm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.chamado import selecionar_chamados
from view.assumir_chamado import Ui_DialogAssumir as Ui_assumir
class Ui_DialogSelect(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(838, 624)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-21, -21, 861, 661))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verdeUserB = QtWidgets.QFrame(self.frame)
        self.verdeUserB.setGeometry(QtCore.QRect(10, 20, 881, 51))
        self.verdeUserB.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB.setObjectName("verdeUserB")
        self.verdeUserB_4 = QtWidgets.QFrame(self.verdeUserB)
        self.verdeUserB_4.setGeometry(QtCore.QRect(410, 30, 881, 51))
        self.verdeUserB_4.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB_4.setObjectName("verdeUserB_4")
        self.verdeUserB_3 = QtWidgets.QFrame(self.frame)
        self.verdeUserB_3.setGeometry(QtCore.QRect(10, 600, 851, 51))
        self.verdeUserB_3.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB_3.setObjectName("verdeUserB_3")
        self.btnAssumir = QtWidgets.QPushButton(self.frame)
        self.btnAssumir.setGeometry(QtCore.QRect(330, 180, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnAssumir.setFont(font)
        self.btnAssumir.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnAssumir.setObjectName("btnAssumir")
        self.banco_adm = QtWidgets.QTableWidget(self.frame)
        self.banco_adm.setGeometry(QtCore.QRect(220, 300, 421, 271))
        self.banco_adm.setObjectName("banco_adm")
        self.banco_adm.setColumnCount(0)
        self.banco_adm.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnAssumir.setText(_translate("Dialog", "Assumir Chamado"))
class TelaChamadoAdm(QtWidgets.QDialog,Ui_DialogSelect):
    def __init__(self):
        super().__init__()
        self.ui = Ui_DialogSelect()
        self.ui.setupUi(self)
        self.setWindowTitle("StudyCall - Administrador")


        self.carregar_chamados()
        self.ui.btnAssumir.clicked.connect(self.abrir_tela_nova)

    def carregar_chamados(self):
     
        try:
            colunas, resultados = selecionar_chamados()  
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erro", f"Erro ao carregar chamados:\n{e}")
            return

        tabela = self.ui.banco_adm
        tabela.setRowCount(len(resultados))
        tabela.setColumnCount(len(colunas))
        tabela.setHorizontalHeaderLabels(colunas)

        for i, linha in enumerate(resultados):
            for j, valor in enumerate(linha):
                tabela.setItem(i, j, QtWidgets.QTableWidgetItem(str(valor)))

        tabela.resizeColumnsToContents()
    def abrir_tela_nova(self):
        self.hide()
        self.tela_assumir=TelaAssumir()
        self.tela_assumir.exec_()
class TelaAssumir(QtWidgets.QDialog,Ui_assumir):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle("StudyCall")
        self.btnAssumeChamado.clicked.connect(self.validar_acesso)
    def validar_acesso(self):
          if self.assumir():
              self.voltar()
    def voltar(self):
        self.hide()
        self.tela_chamados = TelaChamadoAdm()  
        self.tela_chamados.show()

    

   

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
