# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chamado_adm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.chamado import selecionar_chamados
from model.adm_usuario import selecionar_ultimo_id_adm
from view.assumir_chamado import Ui_DialogAssumir as Ui_assumir

class Ui_DialogSelect(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(838, 624)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-21, -21, 861, 661))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verdeUserB = QtWidgets.QFrame(self.frame)
        self.verdeUserB.setGeometry(QtCore.QRect(10, 20, 881, 51))
        self.verdeUserB.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB.setObjectName("verdeUserB")
        self.verdeUserB_4 = QtWidgets.QFrame(self.verdeUserB)
        self.verdeUserB_4.setGeometry(QtCore.QRect(410, 30, 881, 51))
        self.verdeUserB_4.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB_4.setObjectName("verdeUserB_4")
        self.verdeUserB_3 = QtWidgets.QFrame(self.frame)
        self.verdeUserB_3.setGeometry(QtCore.QRect(10, 600, 851, 51))
        self.verdeUserB_3.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB_3.setObjectName("verdeUserB_3")
        self.btnAssumir = QtWidgets.QPushButton(self.frame)
        self.btnAssumir.setGeometry(QtCore.QRect(330, 100, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnAssumir.setFont(font)
        self.btnAssumir.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnAssumir.setObjectName("btnAssumir")
        self.banco_adm = QtWidgets.QTableWidget(self.frame)
        self.banco_adm.setGeometry(QtCore.QRect(50, 200, 771, 401))
        self.banco_adm.setObjectName("banco_adm")
        self.banco_adm.setColumnCount(0)
        self.banco_adm.setRowCount(0)

        self.tableUltimoID = QtWidgets.QTableWidget(self.frame)
        self.tableUltimoID.setGeometry(QtCore.QRect(540, 100, 150, 60)) 
        self.tableUltimoID.setRowCount(1)
        self.tableUltimoID.setColumnCount(1)
        self.tableUltimoID.setHorizontalHeaderLabels(["seu ID:"])
        self.tableUltimoID.setStyleSheet("background-color: #f0f0f0; font: bold 10pt 'Verdana';")
        self.tableUltimoID.horizontalHeader().setStretchLastSection(True)
        self.tableUltimoID.verticalHeader().setVisible(False)
        self.tableUltimoID.horizontalHeader().setFixedHeight(25)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnAssumir.setText(_translate("Dialog", "Assumir Chamado"))
class TelaChamadoAdm(QtWidgets.QDialog,Ui_DialogSelect):
    def __init__(self):
        super().__init__()
        self.ui = Ui_DialogSelect()
        self.ui.setupUi(self)
        self.setWindowTitle("StudyCall - Administrador")
        self.ui.banco_adm.cellClicked.connect(self.selecionar_chamado)
        self.id_chamado_selecionado = None  

        self.carregar_chamados()
        self.mostrar_id_adm()
        self.ui.btnAssumir.clicked.connect(self.abrir_tela_nova)
    def selecionar_chamado(self, row, column):
        try:
            tabela = self.ui.banco_adm
            item_id = tabela.item(row, 0) 
            if item_id:
             self.id_chamado_selecionado = int(item_id.text())
           
            else:
             self.id_chamado_selecionado = None
        except Exception as e:
          print(f"Erro ao selecionar chamado: {e}")
    def carregar_chamados(self):
     
        try:
            colunas, resultados = selecionar_chamados()  
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erro", f"Erro ao carregar chamados:\n{e}")
            return False
        nomes=['id do chamado','assumido por','titulo','descricao','nivel de prioridade','status','local onde ocorreu','usuario','data de abertura','Finalização: prevista ou em']
        self.ui.banco_adm.setRowCount(len(resultados))
        tabela = self.ui.banco_adm
        tabela.setRowCount(len(resultados))
        tabela.setColumnCount(len(colunas))
        tabela.setHorizontalHeaderLabels(nomes)

        for i, linha in enumerate(resultados):
            for j, valor in enumerate(linha):
                 texto = "" if valor is None else str(valor)
                 item = QtWidgets.QTableWidgetItem(texto)
                 item.setTextAlignment(QtCore.Qt.AlignCenter)
                 tabela.setItem(i, j, item)


        tabela.resizeColumnsToContents()
    def mostrar_id_adm(self):
         
     ultimo_id = selecionar_ultimo_id_adm()

     if ultimo_id is not None:
        self.ui.tableUltimoID.setItem(0, 0, QtWidgets.QTableWidgetItem(str(ultimo_id)))
     else:
        self.ui.tableUltimoID.setItem(0, 0, QtWidgets.QTableWidgetItem("Nenhum"))
    def abrir_tela_nova(self):
        if not self.id_chamado_selecionado:
           QtWidgets.QMessageBox.warning(self, "Atenção", "Selecione um chamado primeiro!")
           return False        
        self.hide()
        self.tela_assumir=TelaAssumir()
        self.tela_assumir.dar_valor_ao_id(self.id_chamado_selecionado) 
        self.tela_assumir.exec_()
class TelaAssumir(QtWidgets.QDialog,Ui_assumir):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle("StudyCall")
        self.btnAssumeChamado.clicked.connect(self.validar_acesso)
        self.btnVoltar.clicked.connect(self.retornar)
    def validar_acesso(self):
          if self.assumir():
              self.voltar()
    def voltar(self):
        self.hide()
        self.tela_chamados = TelaChamadoAdm()  
        self.tela_chamados.show()
    def retornar(self):
        self.hide()
        self.tela_chamados = TelaChamadoAdm()  
        self.tela_chamados.show()

    

   

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
