# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facul.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.instituicao import Instituicao
import re

class Ui_DialogFacul(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(673, 494)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-100, -160, 821, 681))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnOkFacul = QtWidgets.QPushButton(self.frame)
        self.btnOkFacul.setGeometry(QtCore.QRect(370, 540, 111, 51))
       
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnOkFacul.setFont(font)
        self.btnOkFacul.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnOkFacul.setObjectName("btnOkFacul")
        self.lineNome = QtWidgets.QLineEdit(self.frame)
        self.lineNome.setGeometry(QtCore.QRect(260, 260, 341, 22))
        self.lineNome.setText("")
        self.lineNome.setObjectName("lineNome")
        self.lineNome.setPlaceholderText('nome da instituicao:')
        self.lineEmail = QtWidgets.QLineEdit(self.frame)
        self.lineEmail.setGeometry(QtCore.QRect(260, 310, 341, 22))
        self.lineEmail.setText("")
        self.lineEmail.setObjectName("lineEmail")
        self.lineEmail.setPlaceholderText('email da instituicao (xx@gmail.xom):')
        self.lineSenha = QtWidgets.QLineEdit(self.frame)
        self.lineSenha.setGeometry(QtCore.QRect(260, 360, 341, 22))
        self.lineSenha.setText("")
        self.lineSenha.setObjectName("lineSenha")
        self.lineSenha.setPlaceholderText('digite uma senha')
        self.lineCnpj = QtWidgets.QLineEdit(self.frame)
        self.lineCnpj.setGeometry(QtCore.QRect(260, 410, 341, 22))
        self.lineCnpj.setText("")
        self.lineCnpj.setObjectName("lineCnpj")
        self.lineCnpj.setPlaceholderText('cnpj da instituicao(xxx-xxxxx)')
        self.nomeUser = QtWidgets.QLabel(self.frame)
        self.nomeUser.setGeometry(QtCore.QRect(410, 240, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nomeUser.setFont(font)
        self.nomeUser.setObjectName("nomeUser")
        self.email = QtWidgets.QLabel(self.frame)
        self.email.setGeometry(QtCore.QRect(410, 290, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.senhaUser = QtWidgets.QLabel(self.frame)
        self.senhaUser.setGeometry(QtCore.QRect(410, 340, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.senhaUser.setFont(font)
        self.senhaUser.setObjectName("senhaUser")
        self.tipoUser = QtWidgets.QLabel(self.frame)
        self.tipoUser.setGeometry(QtCore.QRect(410, 380, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tipoUser.setFont(font)
        self.tipoUser.setObjectName("tipoUser")
        self.verdeUserB = QtWidgets.QFrame(self.frame)
        self.verdeUserB.setGeometry(QtCore.QRect(80, 610, 771, 51))
        self.verdeUserB.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserB.setObjectName("verdeUserB")
        self.verdeUserC = QtWidgets.QFrame(self.frame)
        self.verdeUserC.setGeometry(QtCore.QRect(100, 160, 801, 51))
        self.verdeUserC.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeUserC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeUserC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeUserC.setObjectName("verdeUserC")
        self.tipoUser_2 = QtWidgets.QLabel(self.frame)
        self.tipoUser_2.setGeometry(QtCore.QRect(390, 430, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tipoUser_2.setFont(font)
        self.tipoUser_2.setObjectName("tipoUser_2")
        self.lineMatricula = QtWidgets.QLineEdit(self.frame)
        self.lineMatricula.setGeometry(QtCore.QRect(260, 460, 341, 22))
        self.lineMatricula.setText("")
        self.lineMatricula.setObjectName("lineMatricula")
        self.lineMatricula.setPlaceholderText('matricula')

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnOkFacul.setText(_translate("Dialog", "ok"))
        self.nomeUser.setText(_translate("Dialog", "Nome:"))
        self.email.setText(_translate("Dialog", "Email:"))
        self.senhaUser.setText(_translate("Dialog", "Senha:"))
        self.tipoUser.setText(_translate("Dialog", "Cnpj:"))
        self.tipoUser_2.setText(_translate("Dialog", "Matrícula:"))
    def criar(self):
        global id_facul
        nome=self.lineNome.text().strip()
        email=self.lineEmail.text().strip()
        senha=self.lineSenha.text().strip()
        cnpj=self.lineCnpj.text().strip()
        matricula=self.lineMatricula.text().strip()
        if not nome or not email or not senha or not cnpj or not matricula:
            QtWidgets.QMessageBox.warning(None, "Campos vazios", "Preencha todos os campos antes de salvar!")
            return False
        if not re.fullmatch(r'[\d-]+', matricula ):
            QtWidgets.QMessageBox.warning(None,"ops",'matricula deve ser numero')
            return False
        if not re.fullmatch(r'[\d-]+', cnpj ):
            QtWidgets.QMessageBox.warning(None,"ops",'cnpj deve ser numero')
            return False
        try:
            facul=Instituicao(nome=nome,senha=senha,matricula=matricula,cnpj=cnpj,email=email)
            id_facul=facul.salvar()
            nome_facul=facul.nome
            email_facul=facul.email
            msg=f"""Instituicao cadastrada com sucesso!
            seu id:{id_facul}
            nome: {nome_facul}
            email: {email_facul}
            *id necessario para validar acesso de adm
            """
            QtWidgets.QMessageBox.information(None,"bem vindo",msg)
            return True
        
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Erro ao salvar", f"Ocorreu um erro: {str(e)}")
            return False
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
