# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio_Log.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogInit(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(749, 504)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-11, -11, 761, 521))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verdeCima = QtWidgets.QFrame(self.frame)
        self.verdeCima.setGeometry(QtCore.QRect(0, 0, 771, 51))
        self.verdeCima.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.verdeCima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeCima.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeCima.setObjectName("verdeCima")
        self.verdeCima_2 = QtWidgets.QFrame(self.frame)
        self.verdeCima_2.setGeometry(QtCore.QRect(-10, 470, 771, 51))
        self.verdeCima_2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.verdeCima_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeCima_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeCima_2.setObjectName("verdeCima_2")
        self.textoStudy = QtWidgets.QLabel(self.frame)
        self.textoStudy.setGeometry(QtCore.QRect(330, 80, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(20)
        self.textoStudy.setFont(font)
        self.textoStudy.setObjectName("textoStudy")
        self.btnLogin = QtWidgets.QPushButton(self.frame)
        self.btnLogin.setGeometry(QtCore.QRect(330, 170, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnLogin.setObjectName("btnLogin")
        self.btnCadastro = QtWidgets.QPushButton(self.frame)
        self.btnCadastro.setGeometry(QtCore.QRect(330, 300, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnCadastro.setFont(font)
        self.btnCadastro.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnCadastro.setObjectName("btnCadastro")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textoStudy.setText(_translate("Dialog", "StudyCall"))
        self.btnLogin.setText(_translate("Dialog", "Login"))
        self.btnCadastro.setText(_translate("Dialog", "Cadastro"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
