# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_instituicao.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))  
from controller.instituicao_controle import InstituicaoController

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 731, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 681, 41))
        self.frame_6.setStyleSheet("background-color: rgb(27, 141, 7);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(300, 90, 151, 16))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(-10, 120, 1061, 131))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(270, 30, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(280, 60, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(270, 100, 47, 13))
        self.label_4.setObjectName("label_4")
        self.input_nome = QtWidgets.QLineEdit(self.frame_2)
        self.input_nome.setGeometry(QtCore.QRect(320, 30, 113, 20))
        self.input_nome.setObjectName("input_nome")
        self.input_nome.setPlaceholderText('nome da instituicao')
        self.input_cnpj = QtWidgets.QLineEdit(self.frame_2)
        self.input_cnpj.setGeometry(QtCore.QRect(320, 60, 113, 20))
        self.input_cnpj.setObjectName("input_cnpj")
        self.input_cnpj.setPlaceholderText('cnpj da empresa')
        self.input_senha = QtWidgets.QLineEdit(self.frame_2)
        self.input_senha.setGeometry(QtCore.QRect(320, 100, 113, 20))
        self.input_senha.setObjectName("input_senha")
        self.input_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_senha.setPlaceholderText('senha da instituicao')
        self.btn_olho = QtWidgets.QPushButton(self.frame_2)
        self.btn_olho.setGeometry(QtCore.QRect(435, 100, 30, 20))  
        self.btn_olho.setText("(0)") 
        self.btn_olho.setCheckable(True)  
        self.btn_olho.toggled.connect(
        lambda checked: self.input_senha.setEchoMode(
            QtWidgets.QLineEdit.Normal if checked else QtWidgets.QLineEdit.Password
            )
        )
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 250, 931, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(270, 20, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(110, 50, 191, 20))
        self.label_6.setObjectName("label_6")
        self.input_email = QtWidgets.QLineEdit(self.frame_3)
        self.input_email.setGeometry(QtCore.QRect(310, 20, 113, 20))
        self.input_email.setObjectName("input_email")
        self.input_email.setPlaceholderText('email da instituicao')
        self.input_matricula = QtWidgets.QLineEdit(self.frame_3)
        self.input_matricula.setGeometry(QtCore.QRect(310, 50, 113, 20))
        self.input_matricula.setObjectName("input_matricula")
        self.input_matricula.setPlaceholderText('ex:1928274')
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(0, 330, 791, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 70, 751, 80))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.enviar = QtWidgets.QPushButton(self.frame_4)
        self.enviar.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.enviar.setStyleSheet("background-color: rgb(17, 60, 255);\n"
"color: rgb(255, 255, 255);")
        self.enviar.setObjectName("enviar")
        self.enviar.clicked.connect(self.criar_classe)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Cadastro instituicional:"))
        self.label_2.setText(_translate("Form", "nome:"))
        self.label_3.setText(_translate("Form", "cnpj:"))
        self.label_4.setText(_translate("Form", "senha:"))
        self.label_5.setText(_translate("Form", "email:"))
        self.label_6.setText(_translate("Form", "matricula do administrador de chamdos:"))
        self.enviar.setText(_translate("Form", "entrar"))
    def criar_classe(self):
        nome=self.input_nome.text()
        cnpj=self.input_cnpj.text()
        senha=self.input_senha.text()
        email=self.input_email.text()
        matricula=self.input_matricula.text()
        try:
          facul = InstituicaoController.criar_instituicao(nome, cnpj, senha, email, matricula)
          print(facul)
        except Exception as e:
           QMessageBox.warning(None, "Erro", str(e))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
