# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("tela inicial")
        Form.resize(640, 480)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 731, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(240, 50, 201, 16))
        self.label.setMaximumSize(QtCore.QSize(201, 16777215))
        self.label.setObjectName("label")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 681, 31))
        self.frame_8.setStyleSheet("background-color: rgb(30, 140, 13);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 80, 641, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(240, 40, 121, 16))
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 160, 761, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.usuario = QtWidgets.QPushButton(self.frame_3)
        self.usuario.setGeometry(QtCore.QRect(240, 30, 75, 23))
        self.usuario.setStyleSheet("background-color: rgb(40, 12, 255);\n"
"color: rgb(255, 255, 255);")
        self.usuario.setObjectName("usuario")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(0, 240, 881, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.instituicao = QtWidgets.QPushButton(self.frame_4)
        self.instituicao.setGeometry(QtCore.QRect(240, 20, 75, 23))
        self.instituicao.setStyleSheet("background-color: rgb(40, 12, 255);\n"
"color: rgb(255, 255, 255);")
        self.instituicao.setObjectName("instituicao")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(0, 320, 801, 80))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.adm = QtWidgets.QPushButton(self.frame_5)
        self.adm.setGeometry(QtCore.QRect(240, 10, 75, 23))
        self.adm.setStyleSheet("background-color: rgb(40, 12, 255);\n"
"color: rgb(255, 255, 255);")
        self.adm.setObjectName("adm")
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setGeometry(QtCore.QRect(0, 400, 801, 80))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(0, 49, 651, 41))
        self.frame_7.setStyleSheet("background-color: rgb(30, 140, 13);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">StudyCall</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "logar como:"))
        self.usuario.setText(_translate("Form", "usuario"))
        self.instituicao.setText(_translate("Form", "instituicao"))
        self.adm.setText(_translate("Form", "funcionario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
