# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))  
from model.usuario import Usuario
class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Tela usuario")
        Form.resize(640, 480)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 941, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 641, 41))
        self.frame_6.setStyleSheet("background-color: rgb(46, 143, 4);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 80, 861, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(260, 30, 47, 13))
        self.label_5.setObjectName("label_5")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 160, 931, 91))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.input_nome = QtWidgets.QLineEdit(self.frame_3)
        self.input_nome.setGeometry(QtCore.QRect(240, 20, 113, 20))
        self.input_nome.setObjectName("input_nome")
        self.input_nome.setPlaceholderText('digite seu nome')
        self.input_email = QtWidgets.QLineEdit(self.frame_3)
        self.input_email.setGeometry(QtCore.QRect(240, 60, 113, 20))
        self.input_email.setObjectName("input_email")
        self.input_email.setPlaceholderText("Digite seu email aqui")

        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(190, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(0, 249, 901, 111))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(190, 10, 47, 13))
        self.label_3.setObjectName("label_3")
        self.input_senha = QtWidgets.QLineEdit(self.frame_4)
        self.input_senha.setGeometry(QtCore.QRect(240, 10, 113, 20))
        self.input_senha.setObjectName("input_senha")
        self.input_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_senha.setPlaceholderText('digite sua senha')

        self.btn_olho = QtWidgets.QPushButton(self.frame_4)
        self.btn_olho.setGeometry(QtCore.QRect(360, 10, 30, 20))  
        self.btn_olho.setText("(0)") 
        self.btn_olho.setCheckable(True)  
        self.btn_olho.toggled.connect(
        lambda checked: self.input_senha.setEchoMode(
            QtWidgets.QLineEdit.Normal if checked else QtWidgets.QLineEdit.Password
            )
        )
        self.input_type = QtWidgets.QLineEdit(self.frame_4)
        self.input_type.setGeometry(QtCore.QRect(240, 60, 113, 20))
        self.input_type.setObjectName("input_type")
        self.input_type.setPlaceholderText('professor / aluno')
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(100, 60, 141, 20))
        self.label_4.setObjectName("label_4")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(0, 360, 651, 121))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.enviar = QtWidgets.QPushButton(self.frame_5)
        self.enviar.setGeometry(QtCore.QRect(250, 30, 75, 23))
        self.enviar.setStyleSheet("background-color: rgb(34, 56, 255);\n"
"color: rgb(255, 255, 255);")
        self.enviar.setObjectName("enviar")

        self.enviar.clicked.connect(self.criar_class)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Login:"))
        self.label.setText(_translate("Form", "nome:"))
        self.label_2.setText(_translate("Form", "email:"))
        self.label_3.setText(_translate("Form", "senha:"))
        self.label_4.setText(_translate("Form", "Voce e professor ou aluno:"))
        self.enviar.setText(_translate("Form", "enviar"))
    def criar_class(self):
        nome=self.input_nome.text()
        email=self.input_email.text()
        senha=self.input_senha.text()
        tipo=self.input_type.text()
        tipos=['professor','aluno']   
        if not  nome or not email or not senha or not tipo :
                   QMessageBox.warning(None, "campo nao preenchido", "Complete todos os campos!")
                   return  
        if tipo not in tipos:
             QMessageBox.warning(None,'Desculpe','o ultimo campo so aceita professor ou aluno.')
             
        else:
          user=Usuario(
             nome=nome,
             email=email,
             senha=senha,
             tipo=tipo
          )
          print(user)
       


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
