# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_Adm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.adm_usuario import selecionar_id_por_email_senha_adm

class Ui_DialogAdmLog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        self.id_adm=None
        Dialog.resize(747, 505)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-11, -11, 761, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labEmailAdm = QtWidgets.QLabel(self.frame)
        self.labEmailAdm.setGeometry(QtCore.QRect(350, 160, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labEmailAdm.setFont(font)
        self.labEmailAdm.setObjectName("labEmailAdm")
        self.labSenhaAdm = QtWidgets.QLabel(self.frame)
        self.labSenhaAdm.setGeometry(QtCore.QRect(350, 300, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labSenhaAdm.setFont(font)
        self.labSenhaAdm.setObjectName("labSenhaAdm")
        self.verdeCima = QtWidgets.QFrame(self.frame)
        self.verdeCima.setGeometry(QtCore.QRect(0, 10, 771, 51))
        self.verdeCima.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.verdeCima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeCima.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeCima.setObjectName("verdeCima")
        self.verdeCima_2 = QtWidgets.QFrame(self.frame)
        self.verdeCima_2.setGeometry(QtCore.QRect(0, 470, 771, 51))
        self.verdeCima_2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.verdeCima_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeCima_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeCima_2.setObjectName("verdeCima_2")
        self.lineEmailAdm = QtWidgets.QLineEdit(self.frame)
        self.lineEmailAdm.setGeometry(QtCore.QRect(220, 200, 321, 21))
        self.lineEmailAdm.setObjectName("lineEmailAdm")
        self.lineSenhaAdm = QtWidgets.QLineEdit(self.frame)
        self.lineSenhaAdm.setGeometry(QtCore.QRect(220, 340, 321, 21))
        self.lineSenhaAdm.setObjectName("lineSenhaAdm")
        self.btnLogin = QtWidgets.QPushButton(self.frame)
        self.btnLogin.setGeometry(QtCore.QRect(310, 400, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnLogin.setObjectName("btnLogin")
        self.btnVoltarAdm = QtWidgets.QPushButton(self.frame)
        self.btnVoltarAdm.setGeometry(QtCore.QRect(30, 80, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnVoltarAdm.setFont(font)
        self.btnVoltarAdm.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnVoltarAdm.setObjectName("btnVoltarAdm")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.lineEmailAdm.setPlaceholderText('seu email cadastrado:')
        self.lineSenhaAdm.setPlaceholderText('sua senha cadastrada:')
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labEmailAdm.setText(_translate("Dialog", "Email:"))
        self.labSenhaAdm.setText(_translate("Dialog", "Senha:"))
        self.btnLogin.setText(_translate("Dialog", "Realizar Login"))
        self.btnVoltarAdm.setText(_translate("Dialog", "Voltar"))
    def login_adm(self):
         email=self.lineEmailAdm.text().strip()
         senha=self.lineSenhaAdm.text().strip()
         if not email or not senha:
            QtWidgets.QMessageBox.warning(None,'ops','campo nao preenchido')
            return False
         self.id_adm=selecionar_id_por_email_senha_adm(email=email,senha=senha)
         if self.id_adm is not None:
            QtWidgets.QMessageBox.information(None,'eba','login realizado com sucesso !')
            return True
         else:
            QtWidgets.QMessageBox.warning(None,'ops','acesso inexistente')
            return False
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
