# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from model.usuario import selecionar_id_por_email_senha

class Ui_DialogUserLog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(748, 504)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-11, -11, 761, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verdeCima = QtWidgets.QFrame(self.frame)
        self.verdeCima.setGeometry(QtCore.QRect(0, 10, 771, 51))
        self.verdeCima.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.verdeCima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeCima.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeCima.setObjectName("verdeCima")
        self.verdeCima_2 = QtWidgets.QFrame(self.frame)
        self.verdeCima_2.setGeometry(QtCore.QRect(0, 470, 771, 51))
        self.verdeCima_2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.verdeCima_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeCima_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeCima_2.setObjectName("verdeCima_2")
        self.btnLogin = QtWidgets.QPushButton(self.frame)
        self.btnLogin.setGeometry(QtCore.QRect(340, 380, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnLogin.setObjectName("btnLogin")
        self.labNome = QtWidgets.QLabel(self.frame)
        self.labNome.setGeometry(QtCore.QRect(380, 140, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labNome.setFont(font)
        self.labNome.setObjectName("labNome")
        self.labNome_2 = QtWidgets.QLabel(self.frame)
        self.labNome_2.setGeometry(QtCore.QRect(380, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labNome_2.setFont(font)
        self.labNome_2.setObjectName("labNome_2")
        self.lineEmail = QtWidgets.QLineEdit(self.frame)
        self.lineEmail.setGeometry(QtCore.QRect(270, 180, 281, 21))
        self.lineEmail.setObjectName("lineEmail")
        self.lineSenha = QtWidgets.QLineEdit(self.frame)
        self.lineSenha.setGeometry(QtCore.QRect(270, 290, 291, 21))
        self.lineSenha.setObjectName("lineSenha")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.id_user=None
        self.lineEmail.setPlaceholderText('seu email cadastrado:')
        self.lineSenha.setPlaceholderText('sua senha cadastrada:')
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnLogin.setText(_translate("Dialog", "Realizar Login"))
        self.labNome.setText(_translate("Dialog", "Email:"))
        self.labNome_2.setText(_translate("Dialog", "Senha:"))

    def logar(self):
        email=self.lineEmail.text().strip()
        senha=self.lineSenha.text().strip()
        self.id_user=selecionar_id_por_email_senha(email=email,senha=senha)
        if not email or not senha:
            QtWidgets.QMessageBox.warning(None,'ops','campo nao preenchido')
            return False
        if self.id_user ==None:
            QtWidgets.QMessageBox.warning(None,'ops','acesso inexistente')
            return False
        else:
            QtWidgets.QMessageBox.information(None,'eba','login realizado com sucesso !')
            return True
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
