# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaInicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys



class Ui_DialogInit(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(604, 464)
        self.tela = QtWidgets.QFrame(Dialog)
        self.tela.setGeometry(QtCore.QRect(-10, -10, 641, 491))
        self.tela.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela.setObjectName("tela")
        self.btnAdmin = QtWidgets.QPushButton(self.tela)
        self.btnAdmin.setGeometry(QtCore.QRect(250, 270, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnAdmin.setFont(font)
        self.btnAdmin.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
"border: 2px solid black;")
        self.btnAdmin.setObjectName("btnAdmin")
        self.textoStudy = QtWidgets.QLabel(self.tela)
        self.textoStudy.setGeometry(QtCore.QRect(240, 80, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(20)
        self.textoStudy.setFont(font)
        self.textoStudy.setObjectName("textoStudy")
        self.btnUser = QtWidgets.QPushButton(self.tela)
        self.btnUser.setGeometry(QtCore.QRect(250, 180, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnUser.setFont(font)
        self.btnUser.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnUser.setObjectName("btnUser")
        self.btnInst = QtWidgets.QPushButton(self.tela)
        self.btnInst.setGeometry(QtCore.QRect(250, 350, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btnInst.setFont(font)
        self.btnInst.setStyleSheet("background-color: rgb(35, 173, 4);\n"
"border-radius: 15px;\n"
" border: 2px solid black;")
        self.btnInst.setObjectName("btnInst")
        self.verdeCima = QtWidgets.QFrame(self.tela)
        self.verdeCima.setGeometry(QtCore.QRect(0, 0, 771, 51))
        self.verdeCima.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.verdeCima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeCima.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeCima.setObjectName("verdeCima")
        self.verdeBaixo = QtWidgets.QFrame(self.tela)
        self.verdeBaixo.setGeometry(QtCore.QRect(-80, 420, 771, 51))
        self.verdeBaixo.setStyleSheet("background-color: rgb(25, 170, 0);")
        self.verdeBaixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verdeBaixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verdeBaixo.setObjectName("verdeBaixo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnAdmin.setText(_translate("Dialog", "administrador"))
        self.textoStudy.setText(_translate("Dialog", "StudyCall"))
        self.btnUser.setText(_translate("Dialog", "usuário"))
        self.btnInst.setText(_translate("Dialog", "instituição"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_DialogInit()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
